apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrabble
  namespace: scrabble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrabble
  template:
    metadata:
      labels:
        app: scrabble
    spec:
      containers:
        - name: scrabble
          image: ghcr.io/tayacrystals/scrabble:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
