apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scrabble
  namespace: scrabble
spec:
  ingressClassName: cilium
  rules:
    - host: scrabble.taya.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scrabble
                port:
                  number: 80
