apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-instance
  namespace: keycloak
spec:
  interval: 10m
  dependsOn:
    - name: keycloak-operator
      namespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/tayacluster/infrastructure/keycloak/instance
  prune: true
  wait: true
  timeout: 5m
