apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operator-repository.yaml
  - operator-kustomization.yaml
  - postgres-secret.yaml
  - postgres-kustomization.yaml
  - keycloak-secrets.yaml
  - instance-kustomization.yaml
