apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operator-repository.yaml
  - operator-kustomization.yaml
  - postgres-secret.yaml
  - postgres-cluster.yaml
  - keycloak-secrets.yaml
  - keycloak-instance.yaml
  - ingress.yaml
