apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-oauth
  namespace: oauth2-proxy
spec:
  ingressClassName: cilium
  rules:
    - host: longhorn.taya.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy-longhorn
                port:
                  number: 4180
