apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - secrets.yaml
  - release-longhorn.yaml
  - release-flux.yaml
  - ingress-longhorn.yaml
  - ingress-flux.yaml
