apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: keycloak-https-headers
  namespace: keycloak
spec:
  services:
    - name: keycloak-service
      namespace: keycloak
  backendServices:
    - name: keycloak-service
      namespace: keycloak
  resources:
    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: keycloak-listener
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: keycloak
                route_config:
                  name: keycloak_route
                  virtual_hosts:
                    - name: keycloak_vhost
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: keycloak/keycloak-service
                          request_headers_to_add:
                            - header:
                                key: X-Forwarded-Proto
                                value: https
                              append_action: OVERWRITE_IF_EXISTS_OR_ADD
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
