apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - cert-manager
  - external-secrets
  # - cloudflared  # Uncomment after creating the tunnel secret in Bitwarden
