apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-operator
  - cilium
  - cert-manager
  - external-secrets
  - external-secrets-config
  - cloudflared
  - longhorn
  - cloudnative-pg
  - keycloak
  - keycloak-config
  - oauth2-proxy
  - monitoring
  - tailscale
