apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: keycloak-instance
      namespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/tayacluster/infrastructure/oauth2-proxy
  prune: true
  wait: true
  timeout: 5m
