apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediawiki
  namespace: mediawiki
  labels:
    app: mediawiki
spec:
  ingressClassName: cilium
  rules:
  - host: wiki.taya.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mediawiki
            port:
              number: 80
