apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - localsettings-secret.yaml
  - mariadb-service.yaml
  - mariadb-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
