apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mediawiki-local-settings-php
  namespace: mediawiki
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: mediawiki-local-settings-php
    creationPolicy: Owner
  data:
    - secretKey: LocalSettings.php
      remoteRef:
        key: mediawiki-local-settings-php
