apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  namespace: mediawiki
  labels:
    app: mediawiki
spec:
  selector:
    app: mediawiki
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
